language: node_js

node_js:
- 8

env:
- firebase_auth_domain=hoppers-dev.firebaseapp.com
  firebase_client_email=firebase-adminsdk-t9zxe@hoppers-dev.iam.gserviceaccount.com
  firebase_database_url=https://hoppers-dev.firebaseio.com
  firebase_project_id=hoppers-dev
  firebase_public_api_key=AIzaSyCzUfd5pB1vT4RZCKCojNhhXYobF-xAOvM

cache:
  directories:
  - node_modules

before_install: skip

install:
- yarn install

before_script: skip

script:
- yarn build

after_script:
- yarn start

after_failure:
- echo "The build failed :("